use serde::Deserialize;

// Github repo struct
#[derive(Deserialize, Debug)]
pub struct Repo {
    // pub id: u64,
    // pub node_id: String,
    pub name: String,
    // pub full_name: String,
    // pub private: bool,
    // pub owner: HashMap<String, String>,
    // pub html_url: String,
    // pub description: Option<String>,
    // pub fork: bool,
    // pub url: String,
    // pub forks_url: String,
    // pub keys_url: String,
    // pub collaborators_url: String,
    // pub teams_url: String,
    // pub hooks_url: String,
    // pub issue_events_url: String,
    // pub events_url: String,
    // pub assignees_url: String,
    // pub branches_url: String,
    // pub tags_url: String,
    // pub blobs_url: String,
    // pub git_tags_url: String,
    // pub git_refs_url: String, 
    // pub trees_url: String,
    // pub statuses_url: String,
    // pub languages_url: String,
    // pub stargazers_url: String,
    // pub contributors_url: String,
    // pub subscribers_url: String,
    // pub subscription_url: String,
    // pub commits_url: String,
    // pub git_commits_url: String,
    // pub comments_url: String,
    // pub issue_comment_url: String,
    // pub contents_url: String,
    // pub compare_url: String,
    // pub merges_url: String,
    // pub archive_url: String,
    // pub downloads_url: String,
    // pub issues_url: String,
    // pub pulls_url: String,
    // pub milestones_url: String,
    // pub notifications_url: String,
    // pub labels_url: String,
    // pub releases_url: String,
    // pub deployments_url: String,
    // pub created_at: String,
    // pub updated_at: String,
    // pub pushed_at: String,
    // pub git_url: String,
    // pub ssh_url: String,
    // pub clone_url: String,
    // pub svn_url: String,
    // pub homepage: String,
    // pub size: u32,
    pub stargazers_count: u32,
    // pub watchers_count: u32,
    // pub language: String,
    // pub has_issues: bool,
    // pub has_projects: bool,
    // pub has_downloads: bool,
    // pub has_wiki: bool,
    // pub has_pages: bool,
    // pub has_discussions: bool,
    // pub forks_count: u32,
    // pub mirror_url: Option<String>,
    // pub archived: bool,
    // pub disabled: bool,
    // pub open_issues_count: u32,
    // pub license: Option<String>,
    // pub allow_forking: bool,
    // pub is_template: bool,
    // pub web_commit_signoff_required: bool,
    // pub topics: Vec<String>,
    // pub visibility: String,
    // pub forks: u32,
    // pub open_issues: u32,
    // pub watchers: u32,
    // pub default_branch: String,
}

// Yes, I wrote this massive struct by hand. 
// I thought I needed every field, but I didn't
// In fact, enabling certain feilds just crashes the program